baseURL = 'https://arranwalshe.github.io/qubara.consulting/'
languageCode = 'en-us'
title = 'Qubara Consulting'
theme = 'ananke'

[params]
  text_color = ""
  author = "Qubara Consulting"
  favicon = ""
  site_logo = ""
  description = "Professional consulting services for your business needs"
  background_color_class = "bg-black"
  recent_posts_number = 3
  mainSections = []  # This prevents posts from showing on homepage 